version: "3.8"
services:
  postgres:
    container_name: postgres
    image: arm64v8/postgres:15.3-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres-admin-pwd
    ports:
      - "5432:5432"
  provisioner:
    container_name: provisioner
    build:
      context: .
    environment:
      POSTGRES_ADMIN_URL: postgres://postgres:postgres-admin-pwd@postgres:5432/postgres
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - "./config.example.json:/opt/config/config.json"
